image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- cmd: dotnet restore

after_build:
- choco install opencover.portable
- choco install codecov

build:
  project: package.sln
  parallel: true
  verbosity: minimal

dotnet_csproj:
  patch: false
  file: '**\*.csproj'
  version: $(build_version)
  package_version: $(build_version)
#  file_version: $(APPVEYOR_BUILD_VERSION)
  

test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test"
- codecov -f "results.xml"  

artifacts:
- path: '**\Unity.ServiceLocation.*.nupkg'
  name: 'Unity.ServiceLocation'
  
